### ISSUE TITLE
Chatting

### ISSUE THREAD

**Issue by AshrafMd-1** [AshrafMd-1/pupilfirst-wd401#1]

**Comment by AshrafMd-1** [comment]
Hello miss nightmare

**Comment by Sriparnaduttaa** [comment]
Hii

**Comment by AshrafMd-1** [comment]
Hey

**Comment by AshrafMd-1** [comment]
So you going to clg tmr

**Comment by AshrafMd-1** [comment]
So you going to clg tmr @Sriparnaduttaa

**Comment by Sriparnaduttaa** [comment]
Yes I going

**Comment by AshrafMd-1** [comment]
Great

**Comment by Sriparnaduttaa** [comment]
Yes I going

**Comment by Sriparnaduttaa** [comment]
Good night best of luck for exam

**Comment by AshrafMd-1** [comment]
So how's life

**Comment by AshrafMd-1** [comment]
Don't sleep

**Comment by AshrafMd-1** [comment]
The night is still young

**Comment by Sriparnaduttaa** [comment]
STRESSFUL

**Comment by AshrafMd-1** [comment]
> STRESSFUL 

Sad what me to be your butler

**Comment by Sriparnaduttaa** [comment]
But Im not

**Comment by Sriparnaduttaa** [comment]
> > STRESSFUL 
> 
> Sad what me to be your butler 
No thank you

**Comment by AshrafMd-1** [comment]
> > > STRESSFUL 
> > 
> > Sad what me to be your butler 
> No thank you 

Nvm gd night 
Sweet dreams

**Comment by Sriparnaduttaa** [comment]
> > > > STRESSFUL 
> > > 
> > > Sad what me to be your butler 
> > No thank you 
> 
> Nvm gd night 
> Sweet dreams

😴

**Comment by kharshavardhanr** [comment]
WHYYYYYYYYYYYYY

**Comment by AshrafMd-1** [comment]
> WHYYYYYYYYYYYYY

Its fun

**Comment by kharshavardhanr** [comment]
In what sense

**Comment by kharshavardhanr** [comment]
🥴
